### PR TITLE
Updated display to show pattern number, decrease loading times

### PR DESCRIPTION
**Pull request by gamecat69**
Consequencer: Display now shows the pattern number to make it easier to move to particular patterns during a performance. Also updated the style preferences to match upstream.

CVecorder: Reduced sleep and retries in loadState() to reduce loading times when no CV bank save state files are present.

### CODE REVIEW

**Review by awonak — APPROVED** [review]
LGTM

**Comment by mjaskula** [comment]
I know this is already merged, but the description mentions consequencer and cvrecorder, but the 'files changed' only shows consequencer. Is this right?

**Comment by mjaskula** [comment]
> I know this is already merged, but the description mentions consequencer and cvrecorder, but the 'files changed' only shows consequencer. Is this right?

Nevermind, I see the cvrecorder changes on `main`. It's weird that they're not showing up here though

**Comment by gamecat69** [comment]
I found it strange too! If you notice anything I did wrong with Git please let me know!

Thanks for processing the PR BTW gents.

Kind Regards,
Nik
(Sent from a mobile device)

**Pull request merged**
