### PR TITLE
Add Illustrator and SVG files for panel

### PR DESCRIPTION
**Pull request by roryjamesallen**
Illustrator/SVG files have been made with the same cutouts as the KiCad panel, and the same colour scheme as [Kompari](https://github.com/Allen-Synthesis/Kompari)

These panels have not been ordered yet, but are in the same format as were accepted for the production of Kompari panels, and the same supplier is going to be used to order these for future DIY kits. Using these files is not recommended until I've ordered them to test that they fit, but they are unlikely to have any issues due to being copied in dimensions from the working KiCad panel.

### CODE REVIEW

**Comment by mjaskula** [comment]
I assume that you aren't planning on merging this until you've successfully ordered some? If that's the case I'd say mark this as 'draft' and then merge it when you are happy with the physical panels.

**Comment by roryjamesallen** [comment]
> I assume that you aren't planning on merging this until you've successfully ordered some? If that's the case I'd say mark this as 'draft' and then merge it when you are happy with the physical panels.

Whoops, should've been draft from the start, done now!

**Review by awonak — APPROVED** [review]

**Comment by chrisib** [comment]
What's the current state of this? Any updates since February/March, or is this still on-hold?

**Comment by roryjamesallen** [comment]
Hi guys, sorry about the slow response time. I've replaced the Illustrator and SVG files with the ones used to order the batch of aluminium panels which are currently available to buy in Panel + PCB format at [allensynthesis.co.uk](https://allensynthesis.co.uk), so these are approved files now!

**Pull request merged**
