### PR TITLE
Egressus melodiam (Stepped Melody)

### PR DESCRIPTION
**Pull request by gamecat69**
New script that generates variable length looping patterns of random stepped CV.
Patterns can be linked together into sequences to create rhythmically evolving CV patterns.
Inspired by the Noise Engineering Mimetic Digitalis.

### CODE REVIEW

**Comment by awonak** [comment]
Would you mind cleaning up the sections of commented out blocks of code and giving it a once-over to get ready for review? I'll have some time this weekend to dig in so we can get this reviewed and merged soon.

**Comment by gamecat69** [comment]
Hey @awonak! Thanks for picking this up.
I actually got a bit carried away with this one and decided to add a lot
more functionality. So the script is now quite far off ready for review.

Please let me know if you would prefer to cancel this PR or to put it in
hold somehow until it's ready.

**Comment by awonak** [comment]
I think it would be helpful to put a PR in DRAFT mode if it's still being worked. Ideally hold off on creating a PR until it's really ready for review because the maintainers get an email each time commits are pushed to the PR.

**Comment by gamecat69** [comment]
Sorry for all the commit emails! Closing the PR until I refine a few more things on the script.

**Pull request closed without merging**
