### PR TITLE
Update radio scanner script with latest firmware updates.

### PR DESCRIPTION
**Pull request by awonak**
* Use recommended recommended ticks_diff for timed events on the pico.
* Use constants when possible to make code intention more clear to read.
* Refactor knob reading from integer ranges to using percentage values for easier conversion of different values (oled size / voltage).
* Removed trailing whitespaces.

### CODE REVIEW

**Comment by awonak** [comment]
Fixes #45

**Review by roryjamesallen — CHANGES_REQUESTED** [review]
Much cleaner code than the original, nice!
Only thing is that because the OLED pixels are referenced from 0, using OLED_HEIGHT for example as a multiplier will result in the value overflowing by 1 pixel when at the highest value.
To fix, any time OLED_WIDTH or OLED_HEIGHT are used as a multiplier, they must instead be used as (OLED_WIDTH - 1) for example.
They're only used a couple of times as a multiplier in this program but as an example to others it might be worth defining them as their own variables
e.g.
OLED_MAX_X = OLED_WIDTH - 1

**Comment by roryjamesallen** [comment]
These are the only places that the new variables would need to be used:
```
def x_to_oled(x):
    return round(x * (OLED_WIDTH-1))

def y_to_oled(y):
    return (OLED_HEIGHT-1) - round(y * (OLED_HEIGHT-1))
```

**Comment by awonak** [comment]
Fix applied, thanks for the suggestion!

**Pull request merged**
